[package]
name = "cfuvrand"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
crossterm = "0.28.1"
ratatui = { version = "0.28.1", features = ["crossterm", "unstable-rendered-line-info"] }
tui-textarea = "0.6.1"
