[package]
name = "archipelago_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["tokio-client"]
tokio-client = ["futures-util", "tokio", "tokio-tungstenite", "tungstenite"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
thiserror = "1.0"

futures-util = { version = "0.3", default-features = false, optional = true }
tokio = { version = "1.0", features = ["rt", "macros"], optional = true }
tokio-tungstenite = { version = "0.17", optional = true }
tungstenite = { version = "0.17", optional = true }

[dev-dependencies]
anyhow = "1.0"
